# Generated by Django 2.2 on 2019-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='uploader',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
